In [20]:
import numpy as np

# 3x3 örnek matris
A = np.array([[4, -2,  1],
              [-2, 4, -2],
              [1, -2,  3]])

# 1. Yöntem: NumPy ile özdeğer ve özvektör hesaplama
eigvals1, eigvecs1 = np.linalg.eig(A)

# 2. Yöntem: Karakteristik polinomdan kökleri bulma ve SVD ile null-space üzerinden özvektör hesaplama
coeffs    = np.poly(A)          # Karakteristik polinom katsayıları
eigvals2  = np.real_if_close(np.roots(coeffs))  # Polinom kökleri (özdeğerler)

eigvecs2_list = []
for val in eigvals2:
    M = A - val * np.eye(A.shape[0])
    # Null-space vektörünü SVD ile buluyoruz:
    U, S, Vh = np.linalg.svd(M)
    v = Vh.T[:, -1]                 # Son sütun, en küçük singular value’e karşılık gelir
    v = np.real_if_close(v)         # Küçük kompleks gürültü varsa at
    v = v / np.linalg.norm(v)       # Normalize et
    eigvecs2_list.append(v)

eigvecs2 = np.column_stack(eigvecs2_list)

# Yazdırma
print("NumPy ile hesaplanan Özdeğerler:\n", eigvals1)
print("\nNumPy ile hesaplanan Özvektörler:\n", eigvecs1)

print("\nPolinom köklerinden hesaplanan Özdeğerler:\n", eigvals2)
print("\nSVD tabanlı null-space ile hesaplanan Özvektörler:\n", eigvecs2)

# Sıralı karşılaştırma
print("\nÖzdeğerlerin sıralı halleri karşılaştırması:")
print("NumPy:  ", np.sort(eigvals1))
print("Polinom:", np.sort(eigvals2))


NumPy ile hesaplanan Özdeğerler:
 [7.11902668 2.56837289 1.31260044]

NumPy ile hesaplanan Özvektörler:
 [[ 0.57864919 -0.76930576  0.27080208]
 [-0.66960599 -0.25857088  0.69625349]
 [ 0.46561028  0.58421721  0.66475357]]

Polinom köklerinden hesaplanan Özdeğerler:
 [7.11902668 2.56837289 1.31260044]

SVD tabanlı null-space ile hesaplanan Özvektörler:
 [[-0.57864919  0.76930576  0.27080208]
 [ 0.66960599  0.25857088  0.69625349]
 [-0.46561028 -0.58421721  0.66475357]]

Özdeğerlerin sıralı halleri karşılaştırması:
NumPy:   [1.31260044 2.56837289 7.11902668]
Polinom: [1.31260044 2.56837289 7.11902668]
